name: WordPress Child Theme CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Set PHP version to match your LocalWP (8.3.11)
        extensions: mbstring, xml, dom, json, libxml, tokenizer, xmlwriter, xmlreader, mysqli
        tools: composer, phpunit

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Lint PHP files
      run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit tests/ThemeFunctionsTest.php
